#FROM freekkalter/postgres-supervisord:km
#ADD supervisord.conf /etc/supervisor/conf.d/supervisord.conf
#
#ADD pgpass /pgpass
#RUN chmod 0600 /pgpass
#
#ADD backup.sh /backup.sh
#RUN chmod +x /backup.sh
#
#ADD restore.sh /restore.sh
#RUN chmod +x /restore.sh
#
#EXPOSE 5432
#
#CMD ["/usr/bin/supervisord"]

FROM freekkalter/km:BASE

ADD app /app
