#!/bin/bash

VERSION=9.2
DATADIR=/var/lib/postgresql/$VERSION/main
BINDIR=/usr/lib/postgresql/$VERSION/bin
CONFDIR=/etc/postgresql/$VERSION/main

su postgres sh -c "$BINDIR/postgres --single -D $DATADIR -c config_file=$CONFDIR/postgresql.conf" <<< "CREATE USER docker WITH PASSWORD 'docker';"
su postgres sh -c "$BINDIR/postgres --single -D $DATADIR -c config_file=$CONFDIR/postgresql.conf" <<< "CREATE DATABASE km OWNER=docker ENCODING='UTF8' TEMPLATE=template0;"
su postgres sh -c "$BINDIR/postgres --single -D $DATADIR -c config_file=$CONFDIR/postgresql.conf km" <<< "CREATE TABLE km (\
        id     serial CONSTRAINT pkey PRIMARY KEY,\
        date   date NOT NULL,\
        begin  integer,\
        arnhem integer,\
        laatste integer,\
        terugkomst  integer,\
        comment varchar(200));"
su postgres sh -c "$BINDIR/postgres --single -D $DATADIR -c config_file=$CONFDIR/postgresql.conf km" <<< "ALTER TABLE km OWNER to docker;"
#su postgres sh -c "$BINDIR/postgres -D $DATADIR -c config_file=$CONFDIR/postgresql.conf -c listen_addresses=*"

/usr/bin/supervisord
